server:
  port: 8089

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: role-based-security-service

application:
  security:
    jwt:
      secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      expiration: 3600000 # 1 day
      refresh-token:
        expiration: 60480000 # 7 days